[package]
name = "wdd_common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
console_error_panic_hook = { workspace = true }