[package]
name = "wdd_linuxfoundation"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wdd_common = { path = "../wdd_common" }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }